### PR TITLE
showing repos  to contribute to

### PR DESCRIPTION
**Pull request by dyarawilliams**
Issue #51 completed

### CODE REVIEW

**Comment by mananchawla2005** [comment]
hey can you also make a dark mode of that cause it becomes very weird when u put dark mode on and then go to the /repos endpoint.. it stucks in infinite loop... if u can would be appreciable

**Comment by dyarawilliams** [comment]
I'll give it a try

**Comment by dyarawilliams** [comment]
I might need help with this one I have no idea of what's going on ... @mananchawla2005 Was I supposed to create a new js file and remove the others such as api.js, list-items.js, and input.js from the ejs to do the dark mode. I've tried that but it seems as if the preloader is in an infinite loop as you said.

**Comment by mananchawla2005** [comment]
@dyarawilliams yea even I found it a bit confusing lemme turn on my laptop in a bit and I will trynna debug..

**Comment by dyarawilliams** [comment]
Okay @mananchawla2005 thanks

**Comment by mananchawla2005** [comment]
@dyarawilliams hey I figured out the problem! and its a bigggg oneee lol and not easy to fix... though I found a workround.. just comment out the preloader div in the repos page.. we will keep this page to light mode only!

**Comment by dyarawilliams** [comment]
Alright

**Comment by dyarawilliams** [comment]
I got the dark mode to work I'll push that too

**Comment by dyarawilliams** [comment]
Hacktoberfest-Repository-Checker2

**Comment by mananchawla2005** [comment]
@dyarawilliams thats awesomeeee haha I thought it would be a lot to do.. thankyou so much to do that as well!

**Pull request merged**
