### PR TITLE
added banned repo & PR status checks for api endpoint

### PR DESCRIPTION
**Pull request by sadakchap**
Added checks in `/api` endpoint
- checking for banned repos
- checking Pull requests status
## Issue
[Issue](https://github.com/mananchawla2005/Hacktoberfest-Repo-Checker/issues/10)

### CODE REVIEW

**Comment by mananchawla2005** [comment]
@sadakchap yeah well that's great you are checking for pull in the url too but it would be even nicer if you also check for the label of the pull request contain either hacktoberfest or hacktoberfest-accepted along with the open close status together in json

**Comment by sadakchap** [comment]
@mananchawla2005 , what to show if PR does neither hacktoberfest nor hacktober-accepted as label?

**Comment by sadakchap** [comment]
@mananchawla2005 , do want something like this 
`return res.json({
"error": "Please enter a hacktoberfest Pull Request"
});`

or
`return res.json({
                    "valid": false
                });`

Or do you have any other suggestion?

**Comment by mananchawla2005** [comment]
Valid false would be a nicer way @sadakchap

**Comment by mananchawla2005** [comment]
@sadakchap thanks 🙂

**Pull request merged**
