### PR TITLE
Refactoring Backend

### PR DESCRIPTION
**Pull request by neeraj15022001**
Issue Reference ID : #37 
Issue Creator : @mananchawla2005 
Additional Info : refactored /api till now
Testing : Yet To be Done
Status : In Progress

### CODE REVIEW

**Comment by neeraj15022001** [comment]
@mananchawla2005 can you test api
endpoint name: "/api"
example : "localhost:PORT/api?url=https://github.com/mananchawla2005/Hacktoberfest-Repo-Checker/"
PR-example : "localhost:PORT/api?url=https://github.com/mananchawla2005/Hacktoberfest-Repo-Checker/pull/38"
response-example: "
{
  "status": 200, //Tells about status for GET request
  "isOpen": true, // Tells if PR is open or not
  "isEligible": false, // Tells if Repo is eligible for hactoberfest
  "valid": true // tells if repository data exist/not
}
"
NOTE :

-  In case some key value pair are missing means they are undefined and not known like in case when error occurs while getting repository data
- Status Code "15" means Repository is blocked for hactoberfest
- Status Code "404" means Error occured while retrieving data
- Status Code "200" means Data was retrieved successfully

**Comment by neeraj15022001** [comment]
Once Tested I will be done with backend work too and left with only integrating API calls in frontend part

**Comment by neeraj15022001** [comment]
and ofcourse issue number #31 adding last searched column

**Comment by mananchawla2005** [comment]
@neeraj15022001 It looks great. The api is working fine. U can integrate it with frontend now. And remove the old commented code once its fully working. The not october page also looks good.

**Comment by mananchawla2005** [comment]
> 
> 
> and ofcourse issue number #31 adding last searched column

Yup once this is done, I have some more ideas for further issues. Might have a new page for users to search through eligible repos and filter with language and labels. I have that in projects as a note.

**Comment by neeraj15022001** [comment]
@mananchawla2005 close this PR along with issue #37. I am making a new issue with Frontend Bakend Integration.

**Comment by neeraj15022001** [comment]
Also see if this  can be counted towards hacktoberfest

**Comment by neeraj15022001** [comment]
Refering issue to be continued from here #39

**Pull request closed without merging**
