### PR TITLE
Changed theme for Hacktoberfest 2021

### PR DESCRIPTION
**Pull request by neeraj15022001**
**Issue**: #34 
**Issue Opener**: @mananchawla2005 
**Status**: Implemented
**Additional Information**: API work still to be done
Working Video :
https://user-images.githubusercontent.com/55191873/133342627-d786cd37-fc35-47aa-8159-f7c783898952.mov

### CODE REVIEW

**Comment by mananchawla2005** [comment]
Hey, nice work, can u switch the destination branch to dev instead of master. Also should I merge it rn or you'll add further commits related to api here only?

**Comment by mananchawla2005** [comment]
Also its not responsive yet, hope you working on it :) Once it is reviewed and merge I will add hacktoberfest-accepted label once the hacktoberfest starts so that u get once successful pr

**Comment by mananchawla2005** [comment]
One thing more, the dark mode preference should be stored in local storage :) as it was earlier so that it eases the users.

**Comment by neeraj15022001** [comment]
> Hey, nice work, can u switch the destination branch to dev instead of master. Also should I merge it rn or you'll add further commits related to api here only? 

Ok i will switch the branch

**Comment by neeraj15022001** [comment]
> One thing more, the dark mode preference should be stored in local storage :) as it was earlier so that it eases the users. 

So you want to persist dark mode, okay i will make that change in this code only

**Comment by mananchawla2005** [comment]
> 
> 
> > Hey, nice work, can u switch the destination branch to dev instead of master. Also should I merge it rn or you'll add further commits related to api here only?
> 
> Ok i will switch the branch

Yup great work though. Take your time. There is a lot of time left for hf 2021. Hope the final result comes out best :)

**Comment by neeraj15022001** [comment]
@mananchawla2005 added theme persistancy

**Review by mananchawla2005 — CHANGES_REQUESTED** [review]
image
Yup great work looks fine to me. Just this line is left for responsive. Make it a bit smaller in size in small screens
image
And second this part. The text gets hidden behind the button. 
Third can you make this text box large by animating if the screen size is large. Thanks in advance :)

Yea thats all, awesome work. After these small issues u can work on the api stuff :) @neeraj15022001

**Comment by mananchawla2005** [comment]
@neeraj15022001

**Comment by neeraj15022001** [comment]
@mananchawla2005  review this, in case any bug please ask for changes again.

**Review by mananchawla2005 — CHANGES_REQUESTED** [review]
image
The text don't go beyond that. Rest is fine :)

**Comment by neeraj15022001** [comment]
> image
> The text don't go beyond that. Rest is fine :)

Okay i will check this shortly

**Comment by mananchawla2005** [comment]
> 
> 
> > image
> > The text don't go beyond that. Rest is fine :)
> 
> Okay i will check this shortly

Also idk but for some weird reason, Not able to select the text inside the text box. Give a quick check if u having the same problem at your end and try fixing it if u are able to spot the issue. Everything seemed fine to me. Dk why it happened.

**Comment by neeraj15022001** [comment]
> > > image
> > > The text don't go beyond that. Rest is fine :)
> > 
> > 
> > Okay i will check this shortly
> 
> Also idk but for some weird reason, Not able to select the text inside the text box. Give a quick check if u having the same problem at your end and try fixing it if u are able to spot the issue. Everything seemed fine to me. Dk why it happened.

i disabled selecting on whole page, should i change it?

**Comment by mananchawla2005** [comment]
> 
> 
> > > > image
> > > > The text don't go beyond that. Rest is fine :)
> > > 
> > > 
> > > Okay i will check this shortly
> > 
> > 
> > Also idk but for some weird reason, Not able to select the text inside the text box. Give a quick check if u having the same problem at your end and try fixing it if u are able to spot the issue. Everything seemed fine to me. Dk why it happened.
> 
> i disabled selecting on whole page, should i change it?

Oh yea, enabling it would be better ig, it feels weird.

**Comment by neeraj15022001** [comment]
@mananchawla2005 fixed input field size and tested on all responsive designs, anything else containing bug as of your knowledge?

**Comment by mananchawla2005** [comment]
Maybe U can enable select on the page again. And yea Its good now :) no bugs which I can see @neeraj15022001

**Comment by neeraj15022001** [comment]
> Maybe U can enable select on the page again. And yea Its good now :) no bugs which I can see @neeraj15022001

just skipped from my mind just a second lemme make changes

**Comment by neeraj15022001** [comment]
@mananchawla2005 done from my end

**Comment by mananchawla2005** [comment]
> 
> 
> @mananchawla2005 done from my end

Yup The UI seems good now. Only API left now. U can commit that to this same pull request only.

**Comment by neeraj15022001** [comment]
i just changed the pull request merging branch to dev you can merge later( during hacktoberfest) i will keep working on this one only

**Comment by neeraj15022001** [comment]
we will make this up and working by 2-3 october so it can come in use during hacktoberfest

**Comment by mananchawla2005** [comment]
@neeraj15022001 Well u can do it now also and even If I merge it now, You will get your contribution later too. Last year it was the same. I will just merge it now and add the label of "hacktoberfest-accepted" later. Also It would be nice if u can work on this now since I decided to change the hosting server and have to set it up and test it once and then we can find some bugs if there will be any.

**Comment by neeraj15022001** [comment]
Not a problem it's your wish whenever you want to merge.

**Comment by mananchawla2005** [comment]
> 
> 
> Not a problem it's your wish whenever you want to merge.

Yup I was just waiting for the api stuff. Btw u know why its happening? Like its sending the request to the endpoint but the alert modal box is not coming up. U disabled something? or is it happening with u too?

**Comment by neeraj15022001** [comment]
for now i commented out modal code and i haven't seen and tested API yet will start working on that shortly

**Comment by mananchawla2005** [comment]
@neeraj15022001 okok sure :)

**Comment by neeraj15022001** [comment]
@mananchawla2005 you can close this

**Comment by mananchawla2005** [comment]
> @mananchawla2005 you can close this

merge or close?

**Comment by neeraj15022001** [comment]
Merge

**Comment by neeraj15022001** [comment]
Will this be counted towards hf2021?

**Comment by mananchawla2005** [comment]
> 
> 
> Will this be counted towards hf2021?

Yup I will make sure it does, Just have to add the label when the hf starts

**Pull request merged**
