### PR TITLE
The contributors link was broken, so ⬇️

### PR DESCRIPTION
**Pull request by nemo0**
I thought why not make a readme PR 😛

### CODE REVIEW

**Review by mananchawla2005 — APPROVED** [review]

**Comment by mananchawla2005** [comment]
great thanks!

**Comment by mananchawla2005** [comment]
but u need to make it
to the dev
branch

**Comment by nemo0** [comment]
Oops. Sorry. Let me just create a new PR for the `dev` branch. Feel free to discard this commit.

**Comment by nemo0** [comment]
Please check the latest `dev` branch.

**Pull request closed without merging**
