### PR TITLE
checking for banned repos

### PR DESCRIPTION
**Pull request by sadakchap**
## Issue
[Issue](https://github.com/mananchawla2005/Hacktoberfest-Repo-Checker/issues/2)

Tried checking for banned repos for hacktoberfest

### CODE REVIEW

**Comment by mananchawla2005** [comment]
@sadakchap looks good but the issue need not to be necessarily opened. Just try doing it without providing any state param i guess. 
Otherwise good work 👍

**Comment by sadakchap** [comment]
> @sadakchap looks good but the issue need not to be necessarily opened. Just try doing it without providing any state param i guess.
> Otherwise good work 👍

Yup @mananchawla2005 , I tried it without state param now.

**Comment by mananchawla2005** [comment]
> > @sadakchap looks good but the issue need not to be necessarily opened. Just try doing it without providing any state param i guess.
> > Otherwise good work 👍
> 
> Yup @mananchawla2005 , I tried it without state param now. 

Nice 👍

**Comment by mananchawla2005** [comment]
@sadakchap uh make the pr to develop branch not the master 🙂

**Comment by mananchawla2005** [comment]
@sadakchap bro it shows that there are some conflicts kindly resolve them

**Comment by sadakchap** [comment]
@mananchawla2005 , 

- Added changes for PR check
- resolved conflicts
- removed errors
- rebased pr to dev

Kindly, review the changes and let me know if you want any changes

**Pull request merged**
