### PR TITLE
Hactober-repo-checker-2022

### PR DESCRIPTION
**Pull request by detronetdip**
I am updating  the website with the new theme for the Hactoberfest-2022. I am implementing the dark theme and have updated the logo. If you have any suggestions please leave a comment.

### CODE REVIEW

**Comment by mananchawla2005** [comment]
so far good!!! just one thing if u can look at the dropdown menu button when the size is of mobile width!! also not important but reccomended if u can make it look a bit cooler.. rest all looks good on the dark mode!! I would love if u can do the same for light mode as well!

**Comment by mananchawla2005** [comment]
also take a look at the modal box text color!

**Comment by detronetdip** [comment]
@mananchawla2005  working on it.

**Comment by detronetdip** [comment]
@mananchawla2005  Are we free to change the colour of the logo? Because the logo is looking good in dark theme but in light theme it is not looking so good.

**Comment by mananchawla2005** [comment]
@detronetdip maybe try invert colors adjustment layer in photoshop/photopea? actually they dont have light themed assets this year unfortunately... work on it! if it looks good will keep it else will just disable the color button completely for this year!

**Comment by detronetdip** [comment]
Yes I was thinking the same about disabling the theme switch feature, anyway let me try changing the color first.

**Comment by detronetdip** [comment]
Can we use something like this?

Screenshot from 2022-09-24 01-37-01

I have just increased the colour depth.

**Comment by mananchawla2005** [comment]
well it looks good in black already! try color inverting once instead of increasing color depth?

**Comment by detronetdip** [comment]
Group 4 (1)

Inverted.

**Comment by detronetdip** [comment]
Group 5

Inverted.

**Comment by mananchawla2005** [comment]
looks cool!

**Comment by detronetdip** [comment]
This pull request is ready for review now. @mananchawla2005  please review it and if everything looks good then please merge it after hactoberfest starts and please add hacktoberfest-accepted label as well.

**Comment by mananchawla2005** [comment]
Please look at the color of hamberger icon of dropdown in light mode rest all looks fine! @detronetdip

**Comment by mananchawla2005** [comment]
heyyy!! working on that? @detronetdip

**Comment by detronetdip** [comment]
Yes yes working don't worry

**Comment by detronetdip** [comment]
@mananchawla2005  is everything fine?

**Comment by mananchawla2005** [comment]
yea looks good! sorry I was running sick couldnt reply! @detronetdip

**Comment by detronetdip** [comment]
No problem man I was just checking on you.

**Comment by detronetdip** [comment]
Hey @mananchawla2005 I got to know that If we open a pull request before hactober fest and it gets merge in the hactoberfest it will not be counted so I will close this pull request and will open another one, do not worry the new one will be the same as this one.
Please do not merge this pull request.
Your thought please.

**Comment by mananchawla2005** [comment]
yes thats correct! keep this one as a draft pull request and make a new one when it starts ! @detronetdip

**Comment by detronetdip** [comment]
Ok

**Pull request merged**
