### PR TITLE
Integrated Backend with Frontend

### PR DESCRIPTION
**Pull request by neeraj15022001**
**Issue ID** : #39 
**Status** : Partially Implemented
**Additional information** : 
- [x] Implemented if repo is eligible or not eligible.
- [x] Modal details still need to be updated like if it is opened or closed .
- [x] Hide last searched on focus out
- [x] Create a Preloader on API call requests and before refirecting to website
- [x] Show users last searched column

### CODE REVIEW

**Comment by mananchawla2005** [comment]
looks good. Add messages for prs as well.

**Comment by mananchawla2005** [comment]
@neeraj15022001 
image
hey white modal on dark and dark on white would be better instead. In the current design, Its a little bit hard to distinguish the modal from the body.

**Comment by neeraj15022001** [comment]
@mananchawla2005 I don't feel it will look good

**Comment by mananchawla2005** [comment]
@neeraj15022001 Oh then can u give it a border or something just a little bit for it to be more distinguishable

**Comment by mananchawla2005** [comment]
@neeraj15022001 
image
Also modal sizing might need some work on smaller screens. Maybe a little bit more small.

**Comment by mananchawla2005** [comment]
@neeraj15022001 Would this look good? 
image

**Comment by neeraj15022001** [comment]
yes i think shadow is enough to make it differentiable

**Comment by neeraj15022001** [comment]
if i can add backdrop i will add it it will make it easily distinguishable

**Comment by mananchawla2005** [comment]
> 
> 
> yes i think shadow is enough to make it differentiable

okok sure let this design continue then, just take a look at responsiveness tho

**Comment by neeraj15022001** [comment]
Yeah sure

**Comment by neeraj15022001** [comment]
@mananchawla2005 check changes and inform in case of any bug except that last searched in not hiding on focusing out of input field

**Comment by mananchawla2005** [comment]
Thats one of the issue I found looking further

**Comment by neeraj15022001** [comment]
> 
> Thats one of the issue I found looking further

Fixed

**Comment by mananchawla2005** [comment]
@neeraj15022001 
image
maybe extend its height rather than a scroll and set the value of search box same as the one in history on click if possible and yea rest is fine you can work on other pending tasks now under this pr

**Comment by mananchawla2005** [comment]
@neeraj15022001 hey continue working on this pr, on 1st october I will close this and then u reopen one more pr. good luck

**Comment by neeraj15022001** [comment]
> @neeraj15022001
> image
> maybe extend its height rather than a scroll and set the value of search box same as the one in history on click if possible and yea rest is fine you can work on other pending tasks now under this pr

if we will extend it will cause issue on smaller screen

**Comment by mananchawla2005** [comment]
> 
> 
> > @neeraj15022001
> > image
> > maybe extend its height rather than a scroll and set the value of search box same as the one in history on click if possible and yea rest is fine you can work on other pending tasks now under this pr
> 
> if we will extend it will cause issue on smaller screen

Well then add that click to search kind of feature like what I told above. Thats possible?

**Comment by neeraj15022001** [comment]
> > 
> > 
> > > @neeraj15022001
> > > image
> > > maybe extend its height rather than a scroll and set the value of search box same as the one in history on click if possible and yea rest is fine you can work on other pending tasks now under this pr
> > 
> > if we will extend it will cause issue on smaller screen
> 
> Well then add that click to search kind of feature like what I told above. Thats possible? 

That's implemented but i haven't pushed it yet will push it soon

**Comment by neeraj15022001** [comment]
@mananchawla2005 Just check if anything seems missing or buggy
Changes :
1. Added backdrop to modal to differentiate it from background/
2. Modal now showing if repo is open or not, in case of PR and in normal repository nothing
3.  On focusing out from input field last searched items are now hidiing

**Comment by mananchawla2005** [comment]
All good!!! @neeraj15022001 just one thing is that the click on history thing is not working completely fine. It works but it needs a lot of clicks before it actually does. Most of the times clicking on it, hides the history. Can you do something about it? Rest is fine

**Comment by neeraj15022001** [comment]
> All good!!! @neeraj15022001 just one thing is that the click on history thing is not working completely fine. It works but it needs a lot of clicks before it actually does. Most of the times clicking on it, hides the history. Can you do something about it? Rest is fine

I tested that but not a problem i will check it again

**Comment by neeraj15022001** [comment]
https://user-images.githubusercontent.com/55191873/134966641-a9a68a4d-0495-4fdc-82eb-4ec1a8dce3d0.mov

@mananchawla2005 Check it out here it is working fine

**Comment by mananchawla2005** [comment]
First pne works after that if u try to do it second time it will not @neeraj15022001 and maybe just add the click event for the whole area rather than just the text

**Comment by neeraj15022001** [comment]
> First pne works after that if u try to do it second time it will not @neeraj15022001 and maybe just add the click event for the whole area rather than just the text

Can you share a screen recording for this issue

**Comment by mananchawla2005** [comment]
https://user-images.githubusercontent.com/42414965/135039830-63131e09-29b2-4f0c-a42f-910c2d89d432.mp4

It works but more of a hit or a miss @neeraj15022001

**Comment by neeraj15022001** [comment]
>  Screen.Recording.2021-09-28.at.12.11.09.AM.mov 
> @mananchawla2005 Check it out here it is working fine

here as you can see it is working fine for me but not for you. Hmmm, let me check on other browsers as well and get back to you

**Comment by neeraj15022001** [comment]
> > Screen.Recording.2021-09-28.at.12.11.09.AM.mov
> > @mananchawla2005 Check it out here it is working fine
> 
> here as you can see it is working fine for me but not for you. Hmmm, let me check on other browsers as well and get back to you
try running in incognito tab

**Comment by neeraj15022001** [comment]
it is working for me in chrome's incognito mode also you can try recloning repo again in another destination and opening in chrome's incognito

**Comment by mananchawla2005** [comment]
@neeraj15022001 try on firefox

**Comment by mananchawla2005** [comment]
@neeraj15022001 and if possible make the whole area clickable

**Comment by neeraj15022001** [comment]
> @neeraj15022001 try on firefox

It's working fine for me on firefox as well and i had checked on other device as well it's working. You can try recloning and running again

**Comment by mananchawla2005** [comment]
> 
> 
> > @neeraj15022001 try on firefox
> 
> It's working fine for me on firefox as well and i had checked on other device as well it's working. You can try recloning and running again

Turns out you are right. It works on a real smartphone. Finally!! Thanks alot for all the effort. Hacktoberfest registeration has started you can register now. And make another pr on 1st october. 
Also would you like to work on the gitlab issue as well. This year hf is supporting gitlab too. I self assigned it but currently busy in some work so I dont think I would be able to do so. I was thinking to use this library "https://github.com/jdalrymple/gitbeaker" . Take a look at it. If u can work on this then comment on the gitlab issue, I will assign to it. For this one, u can work over october. No strict time restrictions. Thanks again for all the commits till now :)

**Comment by neeraj15022001** [comment]
I will comment if i want to work on this

**Comment by neeraj15022001** [comment]
hey @mananchawla2005 can i create a PR for this again in October  ? As mentioned this won't be counted towards hacktoberfest as PR is created before

**Comment by mananchawla2005** [comment]
> hey @mananchawla2005 can i create a PR for this again in October  ? As mentioned this won't be counted towards hacktoberfest as PR is created before

I told u that already yes u can. I am not merging this pr. I woul merge the other one

**Pull request closed without merging**
