### PR TITLE
Doc: Modified Demo URL

### PR DESCRIPTION
**Pull request by ashishnpise**
## This PR provides DEMO URL to the Project.

- [x] Changed working Demo URL

### CODE REVIEW

**Review by mananchawla2005 — CHANGES_REQUESTED** [review]
Hey please change all the occurances and u can remove the forward slash at the end!

**Comment by ashishnpise** [comment]
Removed Slash, Hope It helps

**Comment by mananchawla2005** [comment]
Hey please change all the occurances in the api as well

**Comment by ashishnpise** [comment]
> Hey please change all the occurances in the api as well

It should be changed in another pr, This pr is related to url

**Comment by mananchawla2005** [comment]
I am talking about readme only... look closely !

**Comment by ashishnpise** [comment]
Modification of url done

**Pull request merged**
